name: aws-helper
description: performs various functions using the aws-cli
runs:
  using: 'docker'
  image: 'Dockerfile'
# for additional options, see: https://help.github.com/en/articles/metadata-syntax-for-github-actions
